name: Build, Push and Deploy Backend
<<<<<<< HEAD
=======

>>>>>>> 0f9da40ef66913f2b801c8b9133b53729d89f65d
on:
  push:
    branches:
      - main

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t pankajbelote/trekone-backend:latest .

      - name: Push Docker image
        run: |
          docker push pankajbelote/trekone-backend:latest

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /root/trekone
            docker compose pull backend
            docker compose up -d backend
<<<<<<< HEAD
            docker image prune -f
=======
            docker image prune -f
>>>>>>> 0f9da40ef66913f2b801c8b9133b53729d89f65d
